# Settings
Settings:
  enable: true
  keyLength: 15
# The Timeout is in Seconds!
  playerTimeout: 120
# Editable the Plugin Messages
Messages:
  prefix: '&9BetaKey&8: &7'
  noperm: '&cDu hast dazu keine Rechte.'
  playerIsNull: '&cDer Spieler ist nicht Online.'
  commandUse: 'Bitte benutze: &e%command%'
  kickOverdrawn: "&7Du wurdest gekickt! Grund: &eZu viele BetaKey versuche."
  kickTimeout: "&7Du wurdest gekickt! Grund: &eDu hast zu lange gebraucht den Key einzugeben!"
  keyWasCreated: "Der BetaKey wurde &aerfolgreich &7erstellt."
  keyCreated: "Der BetaKey lautet&8: &e%key%"
  notInBeta: "Bitte gebe deinen &eBetaKey &7ein."
  keyNotExist: "Der BetaKey ist nicht registriert."
  keyUsed: "Du hast deinen BetaKey &aerfolgreich &7benutzt."
  removeKey: "Du hast den BetaKey &aerfolgreich &7gelöscht."
  setBetaOn: "Du hast die BetaPhase &aaktiviert."
  setBetaOff: "Du hast die BetaPhase &cdeaktiviert."
  removeBetaPlayer: "Du hast den Spieler &e%playerName% &7seinen Beta Zugang gesperrt."
  addBetaPlayer: "Du hast den Spieler &e%playerName% &7einen Beta Zugang gegeben."
  addedOfflineBetaPlayer: "Der hinzugefügte Spieler ist &cOFFLINE§7, der Spieler wurde zur liste &aerfolgreich &7hinzugefügt."
  notifyAddedPlayer: "Du wurdest &aerfolgreich &7zur Beta hinzugefügt!"